kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active 
  namespace: default
spec:
  selector:
    app: rollout-bluegreen
  type: NodePort
  ports:
  - port: 8080
    name: http

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
  namespace: default
spec:
  selector:
    app: rollout-bluegreen
  type: NodePort
  ports:
  - port: 8080
    name: http
